version: '3.7'
services:
    synobuildenv:
        build:
            context: .
        container_name: synobuildenv
        image: collelog/synobuildenv-ubuntu16.04:master
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./script:/toolkit/script
            - ./results_file:/toolkit/results_file
            - ./results_spk:/toolkit/results_spk
        network_mode: "bridge"
        init: true
        tty: true
