version: '3.7'
services:
    syno-buildenv:
#        build:
#            context: .
        container_name: syno-buildenv
        image: collelog/synology-buildenv
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./results_file:/toolkit/results_file
            - ./results_spk:/toolkit/results_spk
            - ./script:/toolkit/script
        network_mode: "bridge"
        init: true
        tty: true
